# Conexão com o  MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/circulo?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Sophie@16

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
